import 'models/player_game.dart';

class PlayerGamesApi {
  String _cleanName(String name) {
    // Remove all non-letter characters and spaces, then convert to lowercase
    return name.replaceAll(RegExp(r'[^a-zA-Z]'), '').toLowerCase();
  }

  Future<List<PlayerGame>> getPlayerGames(String playerName) async {
    // Mock data - in a real implementation, this would fetch from Supabase
    final cleanedName = _cleanName(playerName);

    if (cleanedName == _cleanName('Felix Hohn')) {
      return [
        PlayerGame(
          id: '1',
          name: 'Felix Hohn',
          matchId: '1',
          lane1: 139,
          lane2: 142,
          lane3: 152,
          lane4: 141,
          total: 574,
          sets: 4,
          points: 1,
        ),
        PlayerGame(
          id: '2',
          name: 'Felix Hohn',
          matchId: '2',
          lane1: 130,
          lane2: 142,
          lane3: 141,
          lane4: 140,
          total: 553,
          sets: 2,
          points: 0,
        ),
        PlayerGame(
          id: '3',
          name: 'Felix Hohn',
          matchId: '3',
          lane1: 115,
          lane2: 139,
          lane3: 130,
          lane4: 135,
          total: 519,
          sets: 2,
          points: 0,
        ),
        PlayerGame(
          id: '4',
          name: 'Felix Hohn',
          matchId: '4',
          lane1: 141,
          lane2: 145,
          lane3: 139,
          lane4: 155,
          total: 580,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '5',
          name: 'Felix Hohn',
          matchId: '5',
          lane1: 148,
          lane2: 135,
          lane3: 136,
          lane4: 145,
          total: 564,
          sets: 2,
          points: 0,
        ),
        PlayerGame(
          id: '6',
          name: 'Felix Hohn',
          matchId: '6',
          lane1: 139,
          lane2: 160,
          lane3: 154,
          lane4: 146,
          total: 599,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '7',
          name: 'Felix Hohn',
          matchId: '7',
          lane1: 143,
          lane2: 141,
          lane3: 111,
          lane4: 153,
          total: 548,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '8',
          name: 'Felix Hohn',
          matchId: '8',
          lane1: 133,
          lane2: 155,
          lane3: 139,
          lane4: 154,
          total: 581,
          sets: 2,
          points: 0,
        ),
        PlayerGame(
          id: '1',
          name: 'Felix Hohn',
          matchId: '1',
          lane1: 156,
          lane2: 135,
          lane3: 152,
          lane4: 152,
          total: 595,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '9',
          name: 'Felix Hohn',
          matchId: '9',
          lane1: 126,
          lane2: 139,
          lane3: 141,
          lane4: 151,
          total: 557,
          sets: 2.5,
          points: 1,
        ),
        PlayerGame(
          id: '10',
          name: 'Felix Hohn',
          matchId: '10',
          lane1: 124,
          lane2: 183,
          lane3: 122,
          lane4: 144,
          total: 573,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '11',
          name: 'Felix Hohn',
          matchId: '11',
          lane1: 149,
          lane2: 140,
          lane3: 158,
          lane4: 146,
          total: 593,
          sets: 4,
          points: 1,
        ),
        PlayerGame(
          id: '12',
          name: 'Felix Hohn',
          matchId: '12',
          lane1: 134,
          lane2: 137,
          lane3: 153,
          lane4: 146,
          total: 570,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '13',
          name: 'Felix Hohn',
          matchId: '13',
          lane1: 151,
          lane2: 130,
          lane3: 135,
          lane4: 155,
          total: 571,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '14',
          name: 'Felix Hohn',
          matchId: '14',
          lane1: 147,
          lane2: 154,
          lane3: 133,
          lane4: 146,
          total: 580,
          sets: 0.5,
          points: 0,
        ),
        PlayerGame(
          id: '14',
          name: 'Felix Hohn',
          matchId: '14',
          lane1: 128,
          lane2: 154,
          lane3: 127,
          lane4: 141,
          total: 550,
          sets: 2,
          points: 1,
        ),
      ];
    } else if (cleanedName == _cleanName('Jane Smith')) {
      return [
        PlayerGame(
          id: '1',
          name: 'Jane Smith',
          matchId: '1',
          lane1: 145,
          lane2: 138,
          lane3: 142,
          lane4: 150,
          total: 575,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '2',
          name: 'Jane Smith',
          matchId: '2',
          lane1: 132,
          lane2: 140,
          lane3: 135,
          lane4: 148,
          total: 555,
          sets: 2,
          points: 0,
        ),
        PlayerGame(
          id: '3',
          name: 'Jane Smith',
          matchId: '3',
          lane1: 120,
          lane2: 135,
          lane3: 128,
          lane4: 130,
          total: 513,
          sets: 2,
          points: 0,
        ),
        PlayerGame(
          id: '4',
          name: 'Jane Smith',
          matchId: '4',
          lane1: 138,
          lane2: 142,
          lane3: 136,
          lane4: 152,
          total: 568,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '5',
          name: 'Jane Smith',
          matchId: '5',
          lane1: 144,
          lane2: 132,
          lane3: 133,
          lane4: 142,
          total: 551,
          sets: 2,
          points: 0,
        ),
        PlayerGame(
          id: '6',
          name: 'Jane Smith',
          matchId: '6',
          lane1: 136,
          lane2: 155,
          lane3: 150,
          lane4: 143,
          total: 584,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '7',
          name: 'Jane Smith',
          matchId: '7',
          lane1: 140,
          lane2: 138,
          lane3: 108,
          lane4: 150,
          total: 536,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '8',
          name: 'Jane Smith',
          matchId: '8',
          lane1: 130,
          lane2: 152,
          lane3: 136,
          lane4: 151,
          total: 569,
          sets: 2,
          points: 0,
        ),
        PlayerGame(
          id: '9',
          name: 'Jane Smith',
          matchId: '9',
          lane1: 153,
          lane2: 132,
          lane3: 149,
          lane4: 149,
          total: 583,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '10',
          name: 'Jane Smith',
          matchId: '10',
          lane1: 123,
          lane2: 140,
          lane3: 138,
          lane4: 148,
          total: 549,
          sets: 2.5,
          points: 1,
        ),
        PlayerGame(
          id: '11',
          name: 'Jane Smith',
          matchId: '11',
          lane1: 122,
          lane2: 180,
          lane3: 120,
          lane4: 141,
          total: 563,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '12',
          name: 'Jane Smith',
          matchId: '12',
          lane1: 146,
          lane2: 137,
          lane3: 150,
          lane4: 143,
          total: 576,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '13',
          name: 'Jane Smith',
          matchId: '13',
          lane1: 148,
          lane2: 128,
          lane3: 132,
          lane4: 152,
          total: 560,
          sets: 3,
          points: 1,
        ),
        PlayerGame(
          id: '14',
          name: 'Jane Smith',
          matchId: '14',
          lane1: 144,
          lane2: 151,
          lane3: 130,
          lane4: 143,
          total: 568,
          sets: 0.5,
          points: 0,
        ),
      ];
    } else {
      // Return empty list for unknown players
      return [];
    }
  }
}
